### ISSUE TITLE
[doc/meta] Build the project requires newer compiler

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [DelphiCodeCoverage/DelphiCodeCoverage#10]
Due to some newer language features used (Low(string), string helper etc) XE2 and probably other later versions couldn't build the project. Would be nice to have it mentioned somewhere and reflected in build.bat

**Comment by Laurensvanrun** [comment]
Which compiler version did you use? I compiled in 10.2.3 and 10.4 without any issues.

**Comment by Fr0sT-Brutal** [comment]
Of course 10x had no issues. I tried with XE2

**Comment by Laurensvanrun** [comment]
Ah, ok, feel free to change the `readme.markdown` and `SetupEnvironment.bat`.

**Comment by Fr0sT-Brutal** [comment]
Done in PR #12 :)

**Comment by Laurensvanrun** [comment]
Thanks!
