### ISSUE TITLE
Link to wizard in readme.md is a bit outdated

### ISSUE THREAD

**Issue by MHumm** [DelphiCodeCoverage/DelphiCodeCoverage#13]
The link in this sentence in the readme: "Please also check out this project as it adds a wizard..."
points to a location which tells one that the project moved to GitHub.

The new link you're pointed there is:
https://github.com/trident-job/delphi-code-coverage-wizard

May I suggest to replace the link in the readme with the new one?

**Comment by ekot1** [comment]
This is updated now. Thank you!
