### ISSUE TITLE
CodeCoverage throws Access_Violations when Tests fail

### ISSUE THREAD

**Issue by LisaFuh** [DelphiCodeCoverage/DelphiCodeCoverage#21]
The tests are created with the DUnitX Framework. Whenever a test fails or an assertion is otherwise thrown I get an Access_Violation and the program stops.
This only happens with win64 Versions, if the tests are build as win32 the program runs as expected. Both Release - win64 and Debug - win64 versions fail.
Run without CodeCoverage the tests also work as expected and the Access_Violation occurs on at least one other machine, so I'm pretty sure it is an issue within CodeCoverage.
I tried changing the jcld21win64.inc file to include dll Exception Hook Support, building the exe myself and using the prebuild exe from the latest Release. There was no difference.
 
System: Windows 10 Pro
Delphi Version : XE7
 
The Log produced with -lt shows this for all used .exe files:
EXCEPTION CODE:0EEDFADE
Address:57114F69
EXCEPTION flags:00000001
EAccessViolation: Zugriffsverletzung bei Adresse 00007FFA4380F7CC in Modul 'dbghelp.dll'. Lesen von Adresse 0000000000000110

Exampletest that triggers the Violation:
procedure Tests.BornToFail;
var i : integer;
begin
    i := 3;
    Assert.isTrue(i = 2);
end;

**Comment by ekot1** [comment]
Could you provide sample project to reproduce this issue?

**Comment by LisaFuh** [comment]
[CC_ACC_VIO_Project.zip](https://github.com/DelphiCodeCoverage/DelphiCodeCoverage/files/8361063/CC_ACC_VIO_Project.zip)

Sure, and thanks already for the quick Answer :)

**Comment by ekot1** [comment]
I've made new release 1.0.15 that should fix this issue

**Comment by LisaFuh** [comment]
It works fine now! Thank you!
