### ISSUE TITLE
Alternative report coverage output for Jenkins reporting

### ISSUE THREAD

**Issue by markhumphreysjhc** [DelphiCodeCoverage/DelphiCodeCoverage#29]
As Emma seems to essentially be abandoned, Emma coverage seems to have been dropped from Jenkins coverage reporting, and the supported coverage tools that is supported are cobertura and jacoco.

**Comment by markhumphreysjhc** [comment]
It seem to get the correct information into Jenkins, although the plugin there seems to assume that the results are java, and get the file names incorrect for packages.

**Comment by ekot1** [comment]
Thank you! It is merged now.
