### ISSUE TITLE
New wizard available

### ISSUE THREAD

**Issue by MHumm** [DelphiCodeCoverage/DelphiCodeCoverage#31]
Hello,

there's a new slightly improved wizard available over here:
[https://github.com/MHumm/delphi-code-coverage-wizard-plus](https://github.com/MHumm/delphi-code-coverage-wizard-plus).

Maybe ypu want to link this in the description as well.

**Comment by ekot1** [comment]
I've updated link in the description

**Comment by MHumm** [comment]
Thanks for updating this! When we can get the other issue with the tool no longer finding source code files resolved the tool will get a major update in the near future, surfacing way more options than it currently surfaces.
